CREATE TABLE client
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_updated_at TIMESTAMP WITHOUT TIME ZONE,
    name            VARCHAR(50)                             NOT NULL,
    email           VARCHAR(50)                             NOT NULL,
    phone_number    INTEGER                                 NOT NULL,
    cpf             INTEGER                                 NOT NULL,
    cnpj            INTEGER                                 NOT NULL,
    firm_name       VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_client PRIMARY KEY (id)
);

CREATE TABLE client_payment_plan
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_updated_at TIMESTAMP WITHOUT TIME ZONE,
    client_id       BIGINT,
    CONSTRAINT pk_client_payment_plan PRIMARY KEY (id)
);

CREATE TABLE post_paid_plan
(
    id           BIGINT         NOT NULL,
    credit_limit DECIMAL(12, 2) NOT NULL,
    credit_spent DECIMAL(12, 2) NOT NULL,
    CONSTRAINT pk_post_paid_plan PRIMARY KEY (id)
);

CREATE TABLE pre_paid_plan
(
    id      BIGINT         NOT NULL,
    credits DECIMAL(12, 2) NOT NULL,
    CONSTRAINT pk_pre_paid_plan PRIMARY KEY (id)
);

ALTER TABLE client
    ADD CONSTRAINT uc_client_cnpj UNIQUE (cnpj);

ALTER TABLE client
    ADD CONSTRAINT uc_client_cpf UNIQUE (cpf);

ALTER TABLE client
    ADD CONSTRAINT uc_client_email UNIQUE (email);

ALTER TABLE client_payment_plan
    ADD CONSTRAINT uc_client_payment_plan_client UNIQUE (client_id);

ALTER TABLE client_payment_plan
    ADD CONSTRAINT FK_CLIENT_PAYMENT_PLAN_ON_CLIENT FOREIGN KEY (client_id) REFERENCES client (id);

ALTER TABLE post_paid_plan
    ADD CONSTRAINT FK_POST_PAID_PLAN_ON_ID FOREIGN KEY (id) REFERENCES client_payment_plan (id);

ALTER TABLE pre_paid_plan
    ADD CONSTRAINT FK_PRE_PAID_PLAN_ON_ID FOREIGN KEY (id) REFERENCES client_payment_plan (id);