CREATE TABLE message
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at            TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    last_updated_at       TIMESTAMP WITHOUT TIME ZONE,
    content               VARCHAR(500)                            NOT NULL,
    sender_id             BIGINT,
    receiver_phone_number INTEGER                                 NOT NULL,
    is_whats_app          BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_message PRIMARY KEY (id)
);

ALTER TABLE message
    ADD CONSTRAINT FK_MESSAGE_ON_SENDER FOREIGN KEY (sender_id) REFERENCES client (id);